### ISSUE TITLE
我实例化控件之后，动画不执行，哪里出问题了

### ISSUE THREAD

**Issue by jiezongnewstar** [ldoublem/LoadingView#10]
实例化之后，配置颜色，探后执行动画，没有效果，只是一张静态的图片

**Comment by ldoublem** [comment]
@jiezongnewstar 哪个类？

**Comment by jiezongnewstar** [comment]
除了旋转动画之外，其他的动画都不执行了，比如ball

**Comment by ldoublem** [comment]
@jiezongnewstar 上代码我看看

**Comment by jiezongnewstar** [comment]
额，我自己里面完全不动，然后就把你的代码download 下来，就旋转的那几个动画可以执行，其他都不执行， 你可以下载你的代码试试。

**Comment by ldoublem** [comment]
@jiezongnewstar 好奇怪  我这边都可以的，你是在模拟器上运行？

**Comment by jiezongnewstar** [comment]
真机上，华为P9 ，7.0的系统

**Comment by ldoublem** [comment]
@jiezongnewstar 我用小米6 系统是7.1.1 也是可以跑起来的  是不是华为系统屏蔽动画了

**Comment by jiezongnewstar** [comment]
那我回头再研究研究吧，谢谢啦
