### ISSUE TITLE
在android7.0中经常出现内存泄漏

### ISSUE THREAD

**Issue by zwping** [ldoublem/LoadingView#12]
在android7.0中经常出现内存泄漏，这个是因为没做适配嘛？

**Comment by ldoublem** [comment]
@zwping 报错信息有么

**Comment by zwping** [comment]
leakcanary中捕捉到了内存泄漏，详细信息如图
![1](https://user-images.githubusercontent.com/26704739/29111712-e76dfc34-7d1d-11e7-8d57-01630b82b964.png)
![2](https://user-images.githubusercontent.com/26704739/29111719-f210812a-7d1d-11e7-9ab9-4b66a83065a4.png)

**Comment by yan885283** [comment]
我的也是这个情况，内存泄露

**Comment by juyao** [comment]
我也是。。。。
