### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ldoublem/LoadingView#13]
I get this:

![image](https://user-images.githubusercontent.com/5357526/37153688-3e7584e8-22e6-11e8-8353-6c53682f36c3.png)

**Comment by ldoublem** [comment]
you can use this code in app build.gradle
compile 'com.ldoublem.loadingview:loadingviewlib:1.0'
@AndroidDeveloperLB

**Comment by AndroidDeveloperLB** [comment]
Please update the project so that all could import it.
