### ISSUE TITLE
为什么给控件设置不了颜色？

### ISSUE THREAD

**Issue by yunsongzh** [ldoublem/LoadingView#14]
用控件对应的.setViewColor()之后发现颜色没变啊！

**Comment by ldoublem** [comment]
@yunsongzh 请问哪个view

**Comment by yunsongzh** [comment]
就是LVEatbeans这个，我在Acticity使用了它的setViewColor()和setEyeColor()方法但是运行的时候颜色都没变。


发自网易邮箱大师
在2018年5月14日 09:50，ldoublem<notifications@github.com> 写道：

@yunsongzh 请问哪个view

**Comment by ldoublem** [comment]
@yunsongzh 你使用这个库是直接用build.gradle compile 的还是代码lib引入的呢？你的运行系统是多少？

**Comment by ldoublem** [comment]
@yunsongzh 检查下初始化代码有没有写错

**Comment by yunsongzh** [comment]
是直接引用的，初始化代码没问题啊！




发自网易邮箱大师
在2018年5月14日 11:57，ldoublem<notifications@github.com> 写道：

@yunsongzh 检查下初始化代码有没有写错

**Comment by yunsongzh** [comment]
在布局文件里使用它，然后在对应的Activity的onCreate()里使用设置颜色的方法啊！




发自网易邮箱大师
在2018年5月14日 11:57，ldoublem<notifications@github.com> 写道：

@yunsongzh 检查下初始化代码有没有写错
