### ISSUE TITLE
You should avoid object allocations during view draw operations

### ISSUE THREAD

**Issue by qbeenslee** [ldoublem/LoadingView#4]
ie:
1. com.ldoublem.loadingView.view.LVCircularCD [L64](https://github.com/ldoublem/LoadingView/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fldoublem%2FloadingView%2Fview%2FLVCircularCD.java#L64), [L73](https://github.com/ldoublem/LoadingView/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fldoublem%2FloadingView%2Fview%2FLVCircularCD.java#L73)
2. com.ldoublem.loadingView.view.LVCircularRing [L59](https://github.com/ldoublem/LoadingView/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fldoublem%2FloadingView%2Fview%2FLVCircularRing.java#L59)
3. com.ldoublem.loadingView.view.LVCircularSmile [L61](https://github.com/ldoublem/LoadingView/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fldoublem%2FloadingView%2Fview%2FLVCircularSmile.java#L61)
4. com.ldoublem.loadingView.view.LVFinePoiStar [L120](https://github.com/ldoublem/LoadingView/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fldoublem%2FloadingView%2Fview%2FLVFinePoiStar.java#L120), [L130](https://github.com/ldoublem/LoadingView/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fldoublem%2FloadingView%2Fview%2FLVFinePoiStar.java#L130)

**Comment by ldoublem** [comment]
thanks
